use crate::input::InputError;
use keyboard_types::Code;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(super) struct MappedKey {
    pub code: Code,
    pub virtual_key: u16,
    pub extended: bool,
}

pub(super) fn resolve_key(code: Code) -> Result<MappedKey, InputError> {
    let (virtual_key, extended) = match code {
        Code::Backquote => (0xC0, false),
        Code::Backslash => (0xDC, false),
        Code::BracketLeft => (0xDB, false),
        Code::BracketRight => (0xDD, false),
        Code::Comma => (0xBC, false),
        Code::Digit0 => (0x30, false),
        Code::Digit1 => (0x31, false),
        Code::Digit2 => (0x32, false),
        Code::Digit3 => (0x33, false),
        Code::Digit4 => (0x34, false),
        Code::Digit5 => (0x35, false),
        Code::Digit6 => (0x36, false),
        Code::Digit7 => (0x37, false),
        Code::Digit8 => (0x38, false),
        Code::Digit9 => (0x39, false),
        Code::Equal => (0xBB, false),
        Code::IntlBackslash => (0xE2, false),
        Code::KeyA => (0x41, false),
        Code::KeyB => (0x42, false),
        Code::KeyC => (0x43, false),
        Code::KeyD => (0x44, false),
        Code::KeyE => (0x45, false),
        Code::KeyF => (0x46, false),
        Code::KeyG => (0x47, false),
        Code::KeyH => (0x48, false),
        Code::KeyI => (0x49, false),
        Code::KeyJ => (0x4A, false),
        Code::KeyK => (0x4B, false),
        Code::KeyL => (0x4C, false),
        Code::KeyM => (0x4D, false),
        Code::KeyN => (0x4E, false),
        Code::KeyO => (0x4F, false),
        Code::KeyP => (0x50, false),
        Code::KeyQ => (0x51, false),
        Code::KeyR => (0x52, false),
        Code::KeyS => (0x53, false),
        Code::KeyT => (0x54, false),
        Code::KeyU => (0x55, false),
        Code::KeyV => (0x56, false),
        Code::KeyW => (0x57, false),
        Code::KeyX => (0x58, false),
        Code::KeyY => (0x59, false),
        Code::KeyZ => (0x5A, false),
        Code::Minus => (0xBD, false),
        Code::Period => (0xBE, false),
        Code::Quote => (0xDE, false),
        Code::Semicolon => (0xBA, false),
        Code::Slash => (0xBF, false),
        Code::AltLeft => (0xA4, false),
        Code::AltRight => (0xA5, true),
        Code::Backspace => (0x08, false),
        Code::CapsLock => (0x14, false),
        Code::ContextMenu => (0x5D, true),
        Code::ControlLeft => (0xA2, false),
        Code::ControlRight => (0xA3, true),
        Code::Enter => (0x0D, false),
        Code::MetaLeft => (0x5B, true),
        Code::MetaRight => (0x5C, true),
        Code::ShiftLeft => (0xA0, false),
        Code::ShiftRight => (0xA1, false),
        Code::Space => (0x20, false),
        Code::Tab => (0x09, false),
        Code::Delete => (0x2E, true),
        Code::End => (0x23, true),
        Code::Help => (0x2F, false),
        Code::Home => (0x24, true),
        Code::Insert => (0x2D, true),
        Code::PageDown => (0x22, true),
        Code::PageUp => (0x21, true),
        Code::ArrowDown => (0x28, true),
        Code::ArrowLeft => (0x25, true),
        Code::ArrowRight => (0x27, true),
        Code::ArrowUp => (0x26, true),
        Code::NumLock => (0x90, false),
        Code::Numpad0 => (0x60, false),
        Code::Numpad1 => (0x61, false),
        Code::Numpad2 => (0x62, false),
        Code::Numpad3 => (0x63, false),
        Code::Numpad4 => (0x64, false),
        Code::Numpad5 => (0x65, false),
        Code::Numpad6 => (0x66, false),
        Code::Numpad7 => (0x67, false),
        Code::Numpad8 => (0x68, false),
        Code::Numpad9 => (0x69, false),
        Code::NumpadAdd => (0x6B, false),
        Code::NumpadDecimal => (0x6E, false),
        Code::NumpadDivide => (0x6F, true),
        Code::NumpadEnter => (0x0D, true),
        Code::NumpadMultiply => (0x6A, false),
        Code::NumpadSubtract => (0x6D, false),
        Code::Escape => (0x1B, false),
        Code::PrintScreen => (0x2C, true),
        Code::ScrollLock => (0x91, false),
        Code::Pause => (0x13, false),
        Code::BrowserBack => (0xA6, true),
        Code::BrowserFavorites => (0xAB, true),
        Code::BrowserForward => (0xA7, true),
        Code::BrowserHome => (0xAC, true),
        Code::BrowserRefresh => (0xA8, true),
        Code::BrowserSearch => (0xAA, true),
        Code::BrowserStop => (0xA9, true),
        Code::LaunchApp1 => (0xB6, true),
        Code::LaunchApp2 => (0xB7, true),
        Code::LaunchMail => (0xB4, true),
        Code::MediaPlayPause => (0xB3, true),
        Code::MediaSelect => (0xB5, true),
        Code::MediaStop => (0xB2, true),
        Code::MediaTrackNext => (0xB0, true),
        Code::MediaTrackPrevious => (0xB1, true),
        Code::Sleep => (0x5F, false),
        Code::AudioVolumeDown => (0xAE, true),
        Code::AudioVolumeMute => (0xAD, true),
        Code::AudioVolumeUp => (0xAF, true),
        Code::F1 => (0x70, false),
        Code::F2 => (0x71, false),
        Code::F3 => (0x72, false),
        Code::F4 => (0x73, false),
        Code::F5 => (0x74, false),
        Code::F6 => (0x75, false),
        Code::F7 => (0x76, false),
        Code::F8 => (0x77, false),
        Code::F9 => (0x78, false),
        Code::F10 => (0x79, false),
        Code::F11 => (0x7A, false),
        Code::F12 => (0x7B, false),
        Code::F13 => (0x7C, false),
        Code::F14 => (0x7D, false),
        Code::F15 => (0x7E, false),
        Code::F16 => (0x7F, false),
        Code::F17 => (0x80, false),
        Code::F18 => (0x81, false),
        Code::F19 => (0x82, false),
        Code::F20 => (0x83, false),
        Code::F21 => (0x84, false),
        Code::F22 => (0x85, false),
        Code::F23 => (0x86, false),
        Code::F24 => (0x87, false),
        _ => return Err(InputError::UnsupportedCode(code)),
    };

    Ok(MappedKey {
        code,
        virtual_key,
        extended,
    })
}
