// This file has been generated by Specta. Do not edit this file manually.
export type ApiResponse = {
	ok: boolean,
};

export type ServerAction = { type: "send-key"; key: ServerKeyName } | { type: "send-shortcut"; shortcut: ServerShortcut } | { type: "paste-text"; text: string };

export type ServerActionRequest = {
	action: ServerAction,
};

export type ServerKeyName = "tab" | "enter" | "backspace";

export type ServerShortcut = "ctrl-c" | "ctrl-v" | "shift-tab";
