// This file has been generated by vibe-coding-remote-server. Do not edit this file manually.
export type ApiResponse = {
	ok: boolean,
};

export type ImportPayload = {
	v: number,
	endpoint: string,
	token: string,
};

export type KeyChord = {
	keys: ServerCode[],
};

export type ServerAction = { type: "input-text"; text: string } | { type: "key-sequence"; sequence: KeyChord[] };

export type ServerActionRequest = {
	action: ServerAction,
};

export type ServerCapabilitiesResponse = {
	supported_codes: ServerCode[],
};

export type ServerCode = string;
