// This file has been generated by vibe-coding-remote-server. Do not edit this file manually.
export type ApiResponse = {
  ok: boolean;
};

export type ImportPayload = {
  v: number;
  endpoint: string;
  token: string;
};

// Matches the serialized names of keyboard_types::Code.
export type ServerCode = string;

export type KeyChord = {
  keys: ServerCode[];
};

export type ServerAction =
  | { type: 'input-text'; text: string }
  | { type: 'key-sequence'; sequence: KeyChord[] };

export type ServerActionRequest = {
  action: ServerAction;
};
