use crate::protocol::{
    ApiResponse, ImportPayload, KeyChord, ServerAction, ServerActionRequest,
    ServerCapabilitiesResponse, ServerCode,
};
use specta::Types;
use specta_typescript::{Exporter, Typescript};
use thiserror::Error;

const TYPESCRIPT_PREAMBLE: &str =
    "// This file has been generated by vibe-coding-remote-server. Do not edit this file manually.";

#[derive(Debug, Error)]
pub(super) enum RenderTypescriptError {
    #[error("failed to apply serde wire-format metadata to exported types: {0}")]
    Serde(#[from] specta_serde::Error),
    #[error("failed to render TypeScript bindings: {0}")]
    Typescript(#[from] specta_typescript::Error),
}

pub(super) fn render_typescript_bindings() -> Result<String, RenderTypescriptError> {
    let types = Types::default()
        .register::<ApiResponse>()
        .register::<ImportPayload>()
        .register::<ServerCode>()
        .register::<ServerCapabilitiesResponse>()
        .register::<KeyChord>()
        .register::<ServerAction>()
        .register::<ServerActionRequest>();

    let resolved_types = specta_serde::apply(types)?;
    let bindings = Exporter::from(Typescript::default())
        .framework_prelude(TYPESCRIPT_PREAMBLE)
        .export(&resolved_types)?;

    Ok(bindings)
}
